version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    links:
      - postgres_db
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: